# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f84d34e10842d757ea17fb2029f4e76e76cda76598e362e36d29019e4f98006bbe16ad61dfc4c3263ebf8eda3c5314c73c2ec6e5072a5785a1f1abc95838d2fd

test:
  secret_key_base: 2e9ee8fd12ae2390ea5c9e84b2d400bb53c2b7447a7048da7f8ab1f64c8310937ef065fdab5884b939ea94a2a6f042a3701347fbfecaa2ef11267cf84789fed5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
